- NuGet.Services.EndToEnd.sln
- scripts/Configure-Environment.ps1
- src/NuGet.Services.EndToEnd/BasicTests.cs
- src/NuGet.Services.EndToEnd/EnvironmentSettings.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/TrustedHttpsCertificatesFixture.cs
This mimics the script used in functional tests to allow running end-to-end tests against the gallery staging slot URL.
The parameters values live in Octopus and are passed to a VSTS build.
> Support fetching staging slot URL in end-to-end test project

- NuGet.Services.EndToEnd.sln
- build.ps1
- buildandtest.ps1
- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/FlatContainerClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SimpleHttpClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V3IndexClient.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/SemVer2FactAttribute.cs
- test.ps1
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
- test/NuGet.Services.EndToEnd.Test/Properties/AssemblyInfo.cs
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTest.cs
- test/NuGet.Services.EndToEnd.Test/project.json
If end-to-end tests need N packages total and the first test is running, push all N packages instead of just the one that the test needs. This means they will all start flowing through V3 at the same time and subsequent tests won't have to wait long for the package to be available.
> Aggressively push end-to-end test packages to minimize test run time

- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
Allow more time for pushing (use the default value used by the client: 5 minutes).
Don't swallow `TaskCanceledException` when pushing since this can lead to a 409 later.
> Use the default push timeout that client uses

- README.md
- src/NuGet.Services.EndToEnd/Support/Clients/FlatContainerClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/TestData.cs
catalog2dnx and catalog2registration jobs do not need a long timeout like catalog2lucene. This shortens the timeout so that the tests fail faster in the error case.
> Shorten timeout of flat container and registration

- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
The test should specifically try to download the version that was pushed not the latest version.  There's a bug (yet to be investigated) blocking downloading the latest version.
> Fix signed package E2E test

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IRetryingAzureManagementAPIWrapper.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RetryingAzureManagementAPIWrapper.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/ExceptionExtensions.cs
- src/NuGet.Services.EndToEnd/Support/RetryUtility.cs
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
- test/NuGet.Services.EndToEnd.Test/Support/ExceptionExtensionsTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/RetryUtilityTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/RetryingAzureManagementAPIWrapperTests.cs
I took a "data driven" approach to adding retries to E2E tests. I looked at all E2E test failures available in VSTS's history and analyzed the failure types. Transient errors fell into two categories:
1. Transient issues encountered while polling the search service, waiting for a package appear.
- `SocketException`
- `TaskCanceledException`
1. Azure Management API being down
- `AzureManagementException`
To avoid retries potentially hiding bugs, I took this minimal approach and only added retries to these exception types and code paths.
We can easily extend the retries in the future as needed.
> Add retry around V2V3SearchClient polling and Azure Management API calls

- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- src/NuGet.Services.EndToEnd/Support/XUnitExtensions/GalleryTestTheoryAttribute.cs
Progress on https://github.com/NuGet/Engineering/issues/1661.
I also need to remove the production slots from E2E configuration files. This will be a separate PR.
Also, make it so `SkipGalleryTests` covers all the things it should. V2 restore tests should be skipped.
> Either test the staging search slot OR all production slots (never both)

- src/NuGet.Services.EndToEnd/Support/Clients/RetryingAzureManagementAPIWrapper.cs
- test/NuGet.Services.EndToEnd.Test/Support/RetryingAzureManagementAPIWrapperTests.cs
A `TaskCanceledException` was thrown when contacting Azure Management API.
https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=42467&_a=summary&view=logs
I added `SocketException` since both can be thrown by awaiting `HttpClient.SendAsync`.
> Retry call to Azure Management API in case of HTTP request failure

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
This will be used to validate the 4.7/4.9 repository signing resources.
Example end-to-end test run on valid index: [#45908](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=45908)
Example end-to-end test run on invalid index (missing 4.9.0 signing resource): [#45987](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=45987)
Part of: https://github.com/NuGet/Engineering/issues/1778
> Update end-to-end tests to use nuget 4.9.1

- build.ps1
- src/NuGet.Services.EndToEnd/Config/Dev.json
- src/NuGet.Services.EndToEnd/Config/Int.json
- src/NuGet.Services.EndToEnd/Config/Prod.json
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/DotNetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SymbolServerClient.cs
- src/NuGet.Services.EndToEnd/Support/EnvironmentSettings.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageCreationContext.cs
- src/NuGet.Services.EndToEnd/Support/PackageProperties.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/TestData.cs
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.TestPortableSymbols/E2E.TestPortableSymbols.csproj
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.TestPortableSymbols/Properties/AssemblyInfo.cs
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.TestPortableSymbols/TestMath.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- src/NuGet.Services.EndToEnd/Support/Utilities/PortableMetadataReader.cs
- src/NuGet.Services.EndToEnd/SymbolsPackageTests.cs
- src/NuGet.Services.EndToEnd/project.json
- test.ps1
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
- test/NuGet.Services.EndToEnd.Test/project.json
This PR adds end to end test for symbols. Addresses https://github.com/NuGet/NuGetGallery/issues/5520
The test basically, builds sample template project and creates nupkg and snupkg with dlls and pdbs respectively. Pushes this to gallery and then listens to the symbol server endpoint for the availability of the PDB.
Had to update the target framework to net46 due to updated client dependencies which were required to allow symbols validations using client code.
Edit: I will add more tests to this as appropriate.
> Add Symbols end to end tests

- src/NuGet.Services.EndToEnd/LicenseTests.cs
Hotfix to unblock the deployment.
Issue to track proper fix: https://github.com/NuGet/Engineering/issues/2034
> Changed the way URLs are validated in license E2E tests

- src/NuGet.Services.EndToEnd/Support/TestDirectory.cs
This E2E run failed.
https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=54261
> Make path shorter due to long path error on CI

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/SearchServiceConfiguration.cs
This means we don't use the direct cloud service (*.cloudapp.net) name when we are not running E2E tests for search service deployment. We use the official DNS found in the service index.
I ran into this problem because I deployed gallery to INT with the new SSL certificate before search. This should be fine.
> Add "UseOfficialDns" to only determine search instance count from Azure management APIs

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/SearchServiceProperties.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/AzureCloudOrSearchServiceDetails.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/GalleryConfiguration.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/SearchServiceConfiguration.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/ServiceDetails.cs
I have added minimal changes required for integration with the existing E2E tests. 
Once we get rid of the search cloud service, the E2E tests can be refactored to remove unnecessary configs. Meanwhile we need these to run the E2E tests on the older search service(cloud services).
I validated these changes with the new config in NuGetBuild Dev USNC and it the build passed just fine.
https://github.com/NuGet/Engineering/issues/2534
> Add support for E2E tests for Azure search infrastructure.

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/SearchServiceConfiguration.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
Address https://github.com/NuGet/NuGetGallery/issues/7320.
With a 30 second wait time introduced and no response caching, total run time went from **14 minutes and 34 seconds** to **38 minutes and 40 seconds**. With response caching the run time is **21 minutes and 29 seconds**.
> Poll for some additional time against Azure Search Service

- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
Useful for running tests locally. Without it it fails with NPE later when accesses a configuration property.
> Early failure for missing configuration file.

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V3IndexClient.cs
This is required while autocomplete is still going to Lucene but search is going to Azure Search. We need to poll both before continuing with the test since the "wait for search availability" method is used in both search and autocomplete tests. In other words, the tests assume that if a package is available in search it is available in autocomplete.
Theoretically we could have a different "poll for autocomplete" method but this has other complexities and in general the test's assumption is fine.
Required for https://github.com/nuget/nugetgallery/issues/7402.
> Poll all search-related endpoints (search+autocomplete) for availability

- src/NuGet.Services.EndToEnd/App.config
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/SymbolsPackageTests.cs
- src/NuGet.Services.EndToEnd/project.json
- test/NuGet.Services.EndToEnd.Test/App.config
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/RetryUtilityTests.cs
- test/NuGet.Services.EndToEnd.Test/project.json
The end-to-end tests failed on my development machine while using Visual Studio 2019:
* Upgrade XUnit to support VS2019 
* Enforce TLS settings
Tests:
* [`Dev-TestJobs`](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=61585)
* [`Dev-TestGalleryUSNCStaging`](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=61587)
Part of https://github.com/nuget/engineering/issues/2686. Also see:
* SDL 1 - Fixes to end-to-end tests https://github.com/NuGet/NuGet.Services.EndToEnd/pull/94
* SDL 2 - Allows us to use HTTPS protected subdomain in search end-to-end tests https://github.com/NuGet/NuGet.Services.EndToEnd/pull/95
* SDL 3 - Updates end-to-end test configs to use HTTPS protected subdomains [NuGetBuild#1114](https://nuget.visualstudio.com/_git/NuGetBuild/pullrequest/11 …
> [SDL 1] Allow end-to-end tests to run from dev machines

- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/LicenseTests.cs
- src/NuGet.Services.EndToEnd/Support/AssemblyMetadataPackageFile.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/DotNetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/SearchServiceConfiguration.cs
- src/NuGet.Services.EndToEnd/Support/TestData.cs
What configuration is set and when?
- **always set**: `GalleryConfiguration.GalleryBaseUrl` - this is the official URL of gallery that is used for asserting things like license URL in V3 (which points to gallery).
- **set when testing gallery staging**: `GalleryConfiguration.ServiceDetails.BaseUrl` - this is the URL of gallery staging slot used during a gallery deployment.
When E2E test runs need to push packages or run other API calls against the gallery, they use the following precedence order:
1. `GalleryConfiguration.ServiceDetails.BaseUrl` - optional
1. `GalleryConfiguration.GalleryBaseUrl` - required
We never need cloud service details for gallery.
What configuration is set and when?
- **set when deploying search staging**: `SearchServiceConfiguration.SingleSearchService` - this is …
> Simplify base URL configuration for gallery and search

- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
The rest of the system allows null search config. When search config is null all of the search information is gathered from the service index. We should be able to do this when there are no more search cloud services.
Also, delete an unused method.
> Allow null search configuration

- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V3IndexClient.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
Progress on https://github.com/NuGet/Engineering/issues/2784
Currently, E2E tests [fail](https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=63169) when run against the non-default registration hive. This happens because one of the tests expects search service responses to contain registration URLs that are rooted to the URLs from service index files. Those are always going to be different when we migrate to a new registration hives.
This update introduces the configuration to allow optional override of expected registration roots.
Also a confusing variables were renamed in the affected test.
> Search test update to override expected registration roots

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/SearchServiceConfiguration.cs
This is necessary since Azure Search is used in every E2E deployment now.
Without out this the non-Azure Search deployments have flaky end-to-end test results.
Currently the Azure Search deployments have this explicitly set to 30 seconds in config.
> Set a default additional polling duration in code

- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
Progress on https://github.com/NuGet/Engineering/issues/2902.
This parameter was added here: https://github.com/NuGet/NuGetGallery/pull/8161
When we start blocking custom OData, we this pattern will break.
> Use hijack=true to avoid search hijack in a more straight forward way

- test.ps1
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
This helps debugging failed tests.
> Log output instead of sending it to no where

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
Update to System.Text.Encodings.Web 5.0.1 version which is compliant.
Address: https://github.com/NuGet/Engineering/issues/3731.
> [Component Governance] Update System.Text.Encodings.Web version.

- build.ps1
End2End tests builds were failing due to missing .net core 2.1 preview installer that it originally used. Now that the https://github.com/NuGet/ServerCommon/pull/379 PR is merged, updating commit hash.
> Using common build tools that pull .net core 3.1

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V3IndexClient.cs
- test/NuGet.Services.EndToEnd.Test/Support/HttpResponseMessageExtensionsTests.cs
Of the past 20 E2E test runs, this is the source of 2 of the failures.
It's not observed on our monitoring sources and always passes on a retry.
This is not worth blocking E2E tests on.
> Retry on Azure Search and CDN DNS resolution failure

- .github/CODEOWNERS
- src/NuGet.Services.EndToEnd/Support/Clients/FlatContainerClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SymbolServerClient.cs
On our test agents, we get DNS resolution failures every so often and we don't want to block E2E tests on this.
Example failure: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=90490&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=05d39475-ccbf-5834-dd1a-48a50eca8e18&l=82
Also add CODEOWNERS file.
> Retry on DNS failure for the CDN and symbols URL

- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SimpleHttpClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SymbolServerClient.cs
- src/NuGet.Services.EndToEnd/Support/HttpClientExtensions.cs
This is to improve debugging and to align with my plan to require User-Agent for the deprecation API.
> Add User-Agent header to requests

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
Fixes: https://github.com/NuGet/Engineering/issues/4704
Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault package dependency. Former one is deprecated.
I manually tested this change in [Gallery dev environment](https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-pipeline-progress&releaseId=1478870)
> Transition from Microsoft.Azure.KeyVault to Azure.Security.KeyVault

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
Related to: https://github.com/NuGet/Engineering/issues/4704
Follow up for comment https://github.com/NuGet/NuGet.Services.EndToEnd/pull/125#discussion_r1320375864, use stable version of Server.Common
> Use stable version of Server.Common

- src/NuGet.Services.EndToEnd/Support/TestData.cs
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.TestPortableSymbols/E2E.TestPortableSymbols.csproj
Our new test agent does not have the .NET 4.0 or .NET 4.6.2 targeting pack. This is easier than updating the test agent.
> Switch to .NET Framework 4.7.2 test package

- src/NuGet.Services.EndToEnd/Support/Clients/DotNetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
E2E tests produce some packages to be used while testing. `dotnet pack` in new SDK [defaults](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack#options) to Release builds, while the rest of the code assumes builds are Debug:
https://github.com/NuGet/NuGet.Services.EndToEnd/blob/d19a29b8a4f808ce428f255dd6d6ceb2eee37dab/src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs#L445-L452
As a result, tests fail to find a package when built on up-to-date agents.
This change forces debug builds of test packages, so it continues to work as before.
Also, fixed typo in `PushedPackagesFixture.cs`, line 158, which seem to have updated line endings (aligning with the rest of the repo). That's why the whole file is marked as changed, switch diff viewer to ignore whitespace changes.
> Forcing debug builds for test packages.

- build.ps1
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Configuration/E2ESecretConfigurationReader.cs
- src/NuGet.Services.EndToEnd/Support/Configuration/EnvVarWrapperSecretReader.cs
For SFI-ES2.1.2 compliance we need to stop using [NuGet-1ES-Hosted-Pool](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/fa8b3229-dc0f-4633-a285-ad597076921d/resourceGroups/nuget-dev-1es-ci/providers/Microsoft.CloudTest/hostedpools/NuGet-1ES-Hosted-Pool/msi) and/or linked [nuget-testvault-ci](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/fa8b3229-dc0f-4633-a285-ad597076921d/resourcegroups/devkeyvault/providers/microsoft.managedidentity/userassignedidentities/nuget-testvault-ci/overview) Managed Identity, which provided access to key vault secrets needed for test run.
As we create new [NuGetGallery End to End Tests](https://dev.azure.com/devdiv/DevDiv/_build?definitionId=27473) pipeline in DevDiv AzDO we need to use SFI …
> Add support for getting secrets from environment variables when running tests
