- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
Adds a test for semverlevel filtering on search endpoints.
@joelverhagen i merged our changes together, but please give it the once over to make sure the merge went more or less correctly.
@xavierdecoster
> Add Search Service E2E

- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/SemVer2InlineDataAttribute.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- src/NuGet.Services.EndToEnd/Support/TrustedHttpsCertificatesFixture.cs
- src/NuGet.Services.EndToEnd/UnlistTests.cs
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/TestSettingsTests.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/3786.
> Add end-to-end test to verify unlisted packages in registration and search

- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/RelistTests.cs
- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/UnlistTests.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/3786.
> Add relist end-to-end test for SemVer 2.0.0

- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/RelistTests.cs
- src/NuGet.Services.EndToEnd/SearchResultTests.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/UnlistTests.cs
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
These are failing right now due to https://github.com/NuGet/NuGetGallery/issues/3868.
I will only merge once the tests are passing in dev environment.
> Add end-to-end tests for build metadata SemVer 2.0.0 packages

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/Clients.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/CommandRunner.cs
- src/NuGet.Services.EndToEnd/Support/CommandRunnerResult.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageCreationContext.cs
- src/NuGet.Services.EndToEnd/Support/PackageDirectory.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/SemVer2TheoryAttribute.cs
- src/NuGet.Services.EndToEnd/Support/SourceType.cs
- src/NuGet.Services.EndToEnd/Support/TestData.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/TestSettingsTests.cs
Addresses a big chunk of https://github.com/NuGet/NuGetGallery/issues/3788.
Tests:
1. nuget.exe install specific version
1. nuget.exe install latest version
1. nuget.exe restore `PackageReference`
> Add end-to-end tests that use nuget.exe

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
Add search/query endpoint. Update Poll to pass semVerLevel=2.0.0, which we need after the change to make ignoreFilter on search/query semVerLevel aware.
@joelverhagen
> Fix waiting on package

- src/NuGet.Services.EndToEnd/AutoCompleteResultTests.cs
Fixes https://github.com/NuGet/Engineering/issues/747
> Ensure the autocomplete tests wait for the package to become available.

- src/NuGet.Services.EndToEnd/Support/TestData.cs
Issue: https://github.com/NuGet/Engineering/issues/801
> Increase E2E timeouts to account for china latency

- src/NuGet.Services.EndToEnd/AutoCompleteResultTests.cs
- src/NuGet.Services.EndToEnd/Config/Prod.json
- src/NuGet.Services.EndToEnd/Support/TestData.cs
@xavierdecoster @cristinamanum Can you verify that these are ready to merge to master?
> [ReleasePrep][2017.09.27]RI of dev into master

- src/NuGet.Services.EndToEnd/Support/TestData.cs
> [ReleasePrep][2017.10.16]RI of dev into master

- src/NuGet.Services.EndToEnd/AutoCompleteResultTests.cs
Disabling flakey autocomplete result check test. See https://github.com/NuGet/NuGetGallery/issues/5407
> RI dev into mater

- src/NuGet.Services.EndToEnd/ConnectivityTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/EnvironmentSettings.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- src/NuGet.Services.EndToEnd/Support/XUnitExtensions/SignedPackageTestFactAttribute.cs
- test.ps1
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
See https://github.com/NuGet/NuGetGallery/issues/5497
> [Package Signing] Add Signed Package Tests

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/EnvironmentSettings.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
- src/NuGet.Services.EndToEnd/Support/XUnitExtensions/SignedPackageTestFactAttribute.cs
- test.ps1
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
See https://github.com/NuGet/NuGetGallery/issues/5497
> [Package Signing] Add Signed Package Tests (#39)

- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
Resolve https://github.com/NuGet/Engineering/issues/1483.
> E2E:  ensure Items properties are non-null

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/NuGetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
Here is an example run: https://nuget.visualstudio.com/NuGetBuild/_build/results?buildId=34801&view=logs
Depends on: https://nuget.visualstudio.com/_git/NuGetBuild/pullrequest/543?_a=overview
Fixes https://github.com/NuGet/Engineering/issues/1205
Fixes https://github.com/NuGet/Engineering/issues/1206
> [Package Signing] Add tests for repository signing

- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6103.
This build has been deleted, but it had a socket exception thrown when polling registration:
https://nuget.visualstudio.com/NuGetBuild/NuGetBuild%20Team/_build/results?buildId=38257&view=results
> Add retry to registration polling

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/FlatContainerClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/ExceptionExtensions.cs
- src/NuGet.Services.EndToEnd/Support/HttpRequestMessageException.cs
- src/NuGet.Services.EndToEnd/Support/HttpResponseMessageExtensions.cs
- test/NuGet.Services.EndToEnd.Test/Support/HttpResponseMessageExtensionsTests.cs
Progress on https://github.com/NuGet/NuGetGallery/issues/6103.
> Retry on 5XX when polling flat container and registration blob storage

- .gitignore
- build.ps1
Tracking: https://github.com/NuGet/Engineering/issues/822
> FxCop tools update

- build.ps1
https://github.com/NuGet/Engineering/issues/1826
> When building with private build tools, copy over configuration file from private build tools

- src/NuGet.Services.EndToEnd/LicenseTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/FlatContainerClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/SimpleHttpClient.cs
- src/NuGet.Services.EndToEnd/Support/FlatContainerStringFileType.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageCreationContext.cs
- src/NuGet.Services.EndToEnd/Support/PackageProperties.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/TestData.cs
- src/NuGet.Services.EndToEnd/SymbolsPackageTests.cs
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
E2E tests for license expression/file.
1. Refactor for flexibility;
2. Add tests for license expression/file. 
Fix: https://github.com/NuGet/NuGetGallery/issues/6535
> E2E tests for license expression/file

- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
recent refactoring work broke symbols e2e test. This fixes it.
> Fix e2e tests regression

- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
Add OData search queries that will reach DB.
> ODataDBSearch

- src/NuGet.Services.EndToEnd/AzureSearchOnlyAttribute.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/PushTests.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
Addresses: https://github.com/NuGet/NuGetGallery/issues/6464 
There is also a new config added for "TestAccountOwner", will send the PR shortly. Verified this test in DEV.
> Add Azure search E2E test to verify owner information

- src/NuGet.Services.EndToEnd/DeprecateTests.cs
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/IGalleryClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/RegistrationClient.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageDeprecationContext.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
https://github.com/nuget/nugetgallery/issues/6852
I've added a tests that deprecates a package.
Had to make some minor changes to the infrastructure to fetch and poll deprecation metadata as well.
> Add end-to-end tests for deprecation

- src/NuGet.Services.EndToEnd/NuGetExeTests.cs
- src/NuGet.Services.EndToEnd/Support/TestSettings.cs
Repository signing has been on forever.
> Remove IsRepositorySigningEnabled flag

- src/NuGet.Services.EndToEnd/Config/Dev.json
- src/NuGet.Services.EndToEnd/Config/Int.json
- src/NuGet.Services.EndToEnd/Config/Prod.json
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/PackageTypeTests.cs
- src/NuGet.Services.EndToEnd/Support/Clients/DotNetExeClient.cs
- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
- src/NuGet.Services.EndToEnd/Support/Package.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.DotnetTool/E2E.DotnetTool.csproj
- src/NuGet.Services.EndToEnd/Support/TestData/E2E.DotnetTool/Program.cs
Address https://github.com/NuGet/NuGetGallery/issues/7755
> Add tests for package type pushing and filtering

- build.ps1
- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- test/NuGet.Services.EndToEnd.Test/NuGet.Services.EndToEnd.Test.csproj
This resolves three Component Governance issues.
> Update dependencies and build SDK

- src/NuGet.Services.EndToEnd/Support/Clients/V2V3SearchClient.cs
Related to https://github.com/NuGet/NuGetGallery/issues/8172
> Add testData=true to queries to see test data

- src/NuGet.Services.EndToEnd/Support/Clients/GalleryClient.cs
Related to https://github.com/NuGet/NuGetGallery/issues/8172
> Add testData=true to V2 autocomplete endpoints

- test.ps1
- test/NuGet.Services.EndToEnd.Test/Support/PushedPackagesFixtureTests.cs
Mitigate https://github.com/NuGet/NuGetGallery/issues/8260.
> Disable flaky test

- .editorconfig
- Directory.Build.props
- NuGet.Services.EndToEnd.sln
* Add static code analysis 
1. Add package reference 
2. Add global editor config
Address: https://github.com/NuGet/Engineering/issues/3417
> Add roslyn analyzer

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
- src/NuGet.Services.EndToEnd/Support/AssemblyMetadataPackageFile.cs
Update newtonsoft.json/Servercommon/NuGet.Client SDK
Address: [#4452](https://github.com/NuGet/Engineering/issues/4452)
> Update package version

- .pipelines/NuGet.Services.EndToEnd-CI.yml
Progress on https://github.com/NuGet/Engineering/issues/5226
> CI Pipeline

- src/NuGet.Services.EndToEnd/AutoCompleteResultTests.cs
- src/NuGet.Services.EndToEnd/Support/PackageType.cs
- src/NuGet.Services.EndToEnd/Support/PushedPackagesFixture.cs
Address: https://github.com/NuGet/Engineering/issues/5850
> Add unicode package Id testing

- src/NuGet.Services.EndToEnd/NuGet.Services.EndToEnd.csproj
Fixes https://github.com/NuGet/Engineering/issues/5975
> Update Azure.Identity to v1.11.4
